server:
  port: 9001
spring:
  application:
    name: registration-center
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
    hostname: peer2
  client:
 #   registerWithEureka: false
  #  fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:9000/eureka/