server:
  port: 9000

spring:
  application:
    name: registration-center

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
    hostname: peer1
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:9001/eureka/