server:
  port: 8000

spring:
  application:
    name: clientA

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, info, mappings, httptrace, refresh
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/